[package]
name = "structured"
version = "0.1.0"
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"

[dependencies]
chrono = "0.4"
csv = "1"
itertools = "0.8"
statistical = "1.0.0"
serde = { version = "1", features = ["derive"] }
